// Placeholder Firebase configuration for the SportsCoachGuides app.
//
// Replace the dummy values with the credentials generated by the
// Firebase console or FlutterFire CLI **without committing them**.
// See docs/firebase.md and docs/firebase_development_guide.md for
// the full workflow on managing environments and secrets.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'FirebaseOptions have not been configured for this platform. '
          'Please provide configuration for your current platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: '1:000000000000:web:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'sportscoachguide-73aea',
    authDomain: 'sportscoachguide-73aea.firebaseapp.com',
    storageBucket: 'sportscoachguide-73aea.appspot.com',
    measurementId: 'REPLACE_WITH_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: '1:000000000000:android:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'sportscoachguide-73aea',
    storageBucket: 'sportscoachguide-73aea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: '1:000000000000:ios:placeholder',
    messagingSenderId: '000000000000',
    projectId: 'sportscoachguide-73aea',
    storageBucket: 'sportscoachguide-73aea.appspot.com',
    iosBundleId: 'com.example.sportsCoachGuide',
    iosClientId: 'REPLACE_WITH_IOS_CLIENT_ID',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_MACOS_API_KEY',
    appId: '1:000000000000:ios:macos-placeholder',
    messagingSenderId: '000000000000',
    projectId: 'sportscoachguide-73aea',
    storageBucket: 'sportscoachguide-73aea.appspot.com',
    iosBundleId: 'com.example.sportsCoachGuide',
    iosClientId: 'REPLACE_WITH_MACOS_CLIENT_ID',
  );
}
